### PR TITLE
Add context manager protocol

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/22)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/22)* status: 1 of 2 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
change the committer, I guess...?

:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/22#-:-LyZUowG5v7Q-uNjB4Hj:b-7fcq7t)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/22)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/22#-LydSk-I6aRjtv6Deofy:-LydSk-J7-sEjvhyar8D:b-c78spe) (no related file):*
--reset-author

---

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/22)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/22#-LydSk-I6aRjtv6Deofy:-LzGyOOk-blutwJbYlaN:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

--reset-author
</blockquote></details>

Done.

---

**Pull request merged**
