### PR TITLE
Update changelog for 1.0 release

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[ChangeLog, line 13 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02WYZ55MZEw8jMiLki:-M02WYZ55MZEw8jMiLkj:b-3j469r) ([raw file](https://github.com/pmem/pmemkv-python/blob/08663126d4f9bb862b4f8524e588783e4a70db3a/ChangeLog#L13)):*
> ```
> 	- Switched from return value based error handling to exception based.
> 	- Switched from text representation of engine configuration json to
> 		dictionary.
> ```

I'd say: "dictionary" -> "dictionary items", perhaps...?
___
*[ChangeLog, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02WP_hESNBru3H1_A6:-M02WP_hESNBru3H1_A7:b-8oiozf) ([raw file](https://github.com/pmem/pmemkv-python/blob/08663126d4f9bb862b4f8524e588783e4a70db3a/ChangeLog#L16)):*
> ```
> 
> 	Other changes:
> 	- Added example for exposing pmemkv as rest-api service
> ```

put punctuation marks at the end of all lines (you missed it here and 1 below)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[ChangeLog, line 16 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02WP_hESNBru3H1_A6:-M02XapG40-SHJUHBYLH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/08663126d4f9bb862b4f8524e588783e4a70db3a/ChangeLog#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put punctuation marks at the end of all lines (you missed it here and 1 below)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[ChangeLog, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02iV6o27grW1ift_vj:-M02iV6pDhbCrZfo6QpG:b-jafo19) ([raw file](https://github.com/pmem/pmemkv-python/blob/ad9ac9ec13bfd2e41094c1e210f8aa6fd51cb881/ChangeLog#L4)):*
> ```
> 	* Version 1.0
> 
> 	This is the first release of pmemkv python binding which guarantees
> ```

bindings
___
*[ChangeLog, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02i6gx2IuTBDD8AZMB:-M02i6gx2IuTBDD8AZMC:b-5s4zmm) ([raw file](https://github.com/pmem/pmemkv-python/blob/ad9ac9ec13bfd2e41094c1e210f8aa6fd51cb881/ChangeLog#L5)):*
> ```
> 
> 	This is the first release of pmemkv python binding which guarantees
> 	backward compatibility.
> ```

.. backward compatibility and supports all of the pmemkv 1.0 features
___
*[ChangeLog, line 12 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02ixMP9kctFBBXKe1w:-M02ixMP9kctFBBXKe1x:b-ju3am5) ([raw file](https://github.com/pmem/pmemkv-python/blob/ad9ac9ec13bfd2e41094c1e210f8aa6fd51cb881/ChangeLog#L12)):*
> ```
> 	- Introduced context manager interface.
> 	- Switched from return value based error handling to exception based.
> 	- Switched from text representation of engine configuration json to
> ```

json configuration

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

___
*[ChangeLog, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02iV6o27grW1ift_vj:-M02m5E85EF0FjR8SDO2:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/ad9ac9ec13bfd2e41094c1e210f8aa6fd51cb881/ChangeLog#L4)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

bindings
</blockquote></details>

Done.
___
*[ChangeLog, line 5 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02i6gx2IuTBDD8AZMB:-M02m5W0AeHSSqwbLfrH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/ad9ac9ec13bfd2e41094c1e210f8aa6fd51cb881/ChangeLog#L5)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

.. backward compatibility and supports all of the pmemkv 1.0 features
</blockquote></details>

Done.
___
*[ChangeLog, line 12 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/38#-M02ixMP9kctFBBXKe1w:-M02mCim5vlcgR4MgvFL:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/ad9ac9ec13bfd2e41094c1e210f8aa6fd51cb881/ChangeLog#L12)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

json configuration
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/38)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)

**Pull request merged**
