### PR TITLE
Throw exceptions in pmemkv_NI

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10)

### CODE REVIEW

**Comment by ldorau** [comment]
@szyrom @igchor @lukaszstolarczuk @karczex fix for python bindings is ready for review

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[kvengine.cc, line 290 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/10#-Lq1Erf51_ZGQjcR5Fbm:-Lq1Erf51_ZGQjcR5Fbn:bujl2ud) ([raw file](https://github.com/pmem/pmemkv-python/blob/79b1c1e6f9b6686c8fa555fa6ff827f79c45fc7c/kvengine.cc#L290)):*
> ```cpp
> 		// create an exception with value 'result'
> 		PyErr_SetObject(PyExc_Exception, PyLong_FromLong(result));
> 		return NULL;
> ```

This should probably be done for all methods, right?
___
*[pmemkv.py, line 245 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/10#-Lq1FH8A-lIafMQJRyyB:-Lq1FH8A-lIafMQJRyyC:b-n4roja) ([raw file](https://github.com/pmem/pmemkv-python/blob/79b1c1e6f9b6686c8fa555fa6ff827f79c45fc7c/pmemkv.py#L245)):*
> ```Python
>     def get(self, key):
>         try:
>             return pmemkv_NI.get(key)
> ```

Can;t we just propagate the exception from NI here?
I mean not having any try: except: at Python level

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[kvengine.cc, line 290 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/10#-Lq1Erf51_ZGQjcR5Fbm:-Lq1IdPh3DMZfoDk8oQG:b9anjtt) ([raw file](https://github.com/pmem/pmemkv-python/blob/79b1c1e6f9b6686c8fa555fa6ff827f79c45fc7c/kvengine.cc#L290)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This should probably be done for all methods, right?
</blockquote></details>

It is already done in pmemkv.py now, so it is kind of design decision where exceptions should be thrown from.
___
*[pmemkv.py, line 245 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/10#-Lq1FH8A-lIafMQJRyyB:-Lq1J39K76uu4Q4FV_8Y:b-g6nh0h) ([raw file](https://github.com/pmem/pmemkv-python/blob/79b1c1e6f9b6686c8fa555fa6ff827f79c45fc7c/pmemkv.py#L245)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can;t we just propagate the exception from NI here?
I mean not having any try: except: at Python level
</blockquote></details>

We can of course, but I have done in for consistency sake, because all methods do
```
raise RuntimeError("pmemkv_*() failed")
````
now.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[kvengine.cc, line 290 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/10#-Lq1Erf51_ZGQjcR5Fbm:-Lq1OJ2X-wKP-3wjCPhs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/79b1c1e6f9b6686c8fa555fa6ff827f79c45fc7c/kvengine.cc#L290)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is already done in pmemkv.py now, so it is kind of design decision where exceptions should be thrown from.
</blockquote></details>

Done.
___
*[pmemkv.py, line 245 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/10#-Lq1FH8A-lIafMQJRyyB:-Lq1OKy8Dvpf_51Jvs5E:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/79b1c1e6f9b6686c8fa555fa6ff827f79c45fc7c/pmemkv.py#L245)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We can of course, but I have done in for consistency sake, because all methods do
```
raise RuntimeError("pmemkv_*() failed")
````
now.
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10#-:-Lq5mV6sC52-ZCgiiVQ2:bnfp4nl)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10#-:-Lq6JqS90qZp28Gmp1MV:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10#-:-Lq6YQZ30kJxckkVXFJD:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @igchor and @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
