### PR TITLE
update README.md for 1.0 release

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
preview: https://github.com/lukaszstolarczuk/pmemkv-python/tree/update-README.md

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/32)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/32#-M-oUWQPDdab7RqjTsyY:-M-oUWQPDdab7RqjTsyZ:b9kopo) ([raw file](https://github.com/pmem/pmemkv-python/blob/d75cf31a231faf03f99874b765535a59bdce1781/README.md#L6)):*
> ```Markdown
> Python bindings for pmemkv.
> 
> All known issues and limitations are logged as GitHub issues.
> ```

... or are described in man pages

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[README.md, line 6 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/32#-M-oUWQPDdab7RqjTsyY:-M-odPvx2HTf95_oiyv6:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/d75cf31a231faf03f99874b765535a59bdce1781/README.md#L6)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

... or are described in man pages
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/32)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[README.md, line 20 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/32#-M-yCwak2OSrZdjGtUQ7:-M-yCwak2OSrZdjGtUQ8:bo1yssj) ([raw file](https://github.com/pmem/pmemkv-python/blob/c9fe393c72dcf8eadb113dc7809d36781de6c504/README.md#L20)):*
> ```Markdown
> 
> Start by installing [pmemkv](https://github.com/pmem/pmemkv/blob/master/INSTALLING.md)
> (currently at best **in version 1.0.2**) on your system.
> ```

I would change that to at best 1.0.2 or 1.1 (it will work with 1.1 after all and it has some performance improvements)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[README.md, line 20 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/32#-M-yCwak2OSrZdjGtUQ7:-M-ykUU8DMjIDF3AevhK:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c9fe393c72dcf8eadb113dc7809d36781de6c504/README.md#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would change that to at best 1.0.2 or 1.1 (it will work with 1.1 after all and it has some performance improvements)
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/32#-:-M-ywgD33z2-uBvOGFgG:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request merged**
