### PR TITLE
Update build dependencies

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/28)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/28)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/images/install-pmdk.sh, line 56 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/28#-M-KjfPZ19k3GpYYyY09:-M-KjfPZ19k3GpYYyY0A:b-f6xt08) ([raw file](https://github.com/pmem/pmemkv-python/blob/73645aaefd72d0232e825f2686fe87bddba2dff7/utils/docker/images/install-pmdk.sh#L56)):*
> ```Shell
> 		sudo dpkg -i dpkg/libpmem_*.deb dpkg/libpmem-dev_*.deb
> 		sudo dpkg -i dpkg/libpmemobj_*.deb dpkg/libpmemobj-dev_*.deb
> 		sudo dpkg -i dpkg/pmreorder_*.deb
> ```

I'd remove it

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/28)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau and @lukaszstolarczuk)

___
*[utils/docker/images/install-pmdk.sh, line 56 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/28#-M-KjfPZ19k3GpYYyY09:-M-KsB3tD1g6JzZaDPoi:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/73645aaefd72d0232e825f2686fe87bddba2dff7/utils/docker/images/install-pmdk.sh#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd remove it
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
