### PR TITLE
Configure setup for PyPi

### PR DESCRIPTION
**Pull request by karczex**
Follow python packing guide in  setup implementation.

https://packaging.python.org/tutorials/packaging-projects/
https://github.com/pypa/sampleproject/blob/master/setup.py

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/37)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/37)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[setup.py, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/37#-M01jyr96ENS7SZe25GQ:-M01jyr96ENS7SZe25GR:b-8mxykc) ([raw file](https://github.com/pmem/pmemkv-python/blob/d237379a2d63032fcc5ba376be3ab8a6c307caca/setup.py#L2)):*
> ```Python
> """
>  * Copyright 2019, Intel Corporation
> ```

-2020

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/37#-:-M01yDrV2_7-CnnUWwb6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/37)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[setup.py, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/37#-M01jyr96ENS7SZe25GQ:-M02FzwP9F3hra9Kr8XT:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/d237379a2d63032fcc5ba376be3ab8a6c307caca/setup.py#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2020
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/37#-:-M02XoLT8n-uVbW3akoj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/37#-:-M02jLdT52Of9jG2sUR4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
