### PR TITLE
Refactor part one

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)

### CODE REVIEW

**Comment by szyrom** [comment]
@llugin could you review?

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[pmemkv/kvengine.cc, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYMINZ4WdjzHq1yilQ:-LuYMINZ4WdjzHq1yilR:b-spy5vj) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L32)):*
> ```cpp
>  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
>  */
> #define PY_SSIZE_T_CLEAN
> ```

What is it for? Maybe add some comment?
___
*[pmemkv/kvengine.cc, line 59 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYNSbu5FNwBZdAMNv7:-LuYNSbu5FNwBZdAMNv8:b-kv9xgg) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L59)):*
> ```cpp
> static PyObject *
> Pmemkv_new(PyTypeObject *type, PyObject *args, PyObject *kwds) {
> 	PmemkvObject *self;
> ```

why split declaration and assignment?
___
*[pmemkv/kvengine.cc, line 460 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYOfTp4_-sQ9QUBvAl:-LuYOfTp4_-sQ9QUBvAm:biwqkgk) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L460)):*
> ```cpp
> 	.tp_getset = 0,
> 	.tp_base = 0,
>         .tp_dict = NULL,
> ```

wrong alignment?
___
*[pmemkv/pmemkv.py, line 36 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYPf5YDQ7-6JMK5Rh1:-LuYPf5Z21h9qIFYAHLf:b-pvifvf) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L36)):*
> ```Python
> 
> class Database():
>     PMEMKV_STATUS_OK = 0
> ```

Hm, I'm not sure if those should  be inside Database(). It's possible that those values will be used for some other type (for example, in C/C++ config functions also return statuses - this is not the case for Python, but in future something could need those).
___
*[pmemkv/pmemkv.py, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYQUZ58gDs90zbuz4C:-LuYQUZ58gDs90zbuz4D:bwj9mxy) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L56)):*
> ```Python
>     # Takes engine name and configuration from the end user.
>     def __init__(self, engine, config):
>         self.__stopped = False
> ```

We probably don't need __stopped variable anymore. We could implement stopped as checking whether db pointer is NULL (at the NI level)
___
*[pmemkv/pmemkv.py, line 191 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYR7822sFm80S6RYOi:-LuYR7822sFm80S6RYOj:blbtpyn) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L191)):*
> ```Python
>     # Fetches all the key/value pairs present, between key1 and key2 from pmemkv datastore and encodes them.
>     # Takes key1, key2, callback and encoding algorithm from the end user and sends the resulted encoded key/value pairs through callback.
>     def get_string_between(self, key1, key2, func, encoding = 'utf-8'):
> ```

As we talked offline,  *_string_* functions should probably be removed. If not in this PR maybe at least create some issue?

**Review by llugin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/nontrivial_data_tests.py, line 41 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYWgr400LhAF0idtkz:-LuYWgr400LhAF0idtl-:bksz18y) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L41)):*
> ```Python
> 
> class TestNaughtyStrings(unittest.TestCase):
> ```

use single whitelines inside classes
___
*[tests/nontrivial_data_tests.py, line 44 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYa0Ww2SRcTK-3WECC:-LuYa0Ww2SRcTK-3WECD:b9m3xmb) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L44)):*
>super(self.\_\_class\_\_, self)

I believe it's equivalent with just 'super() ' (with no arguments)
___
*[tests/nontrivial_data_tests.py, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYc4_BCz9YPxCrweg-:-LuYc4_BCz9YPxCrweg0:bbsa0qa) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L56)):*
> ```Python
>             try:
>                 urllib.request.urlretrieve(url, file_name)
>             except Exception as e:
> ```

I would catch URLError first ( https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve ), then general Exception
___
*[tests/pmemkv_tests.py, line 39 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYdAkDBpqE9CcFeQDT:-LuYdAkDBpqE9CcFeQDU:b3kqx) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/pmemkv_tests.py#L39)):*
> ```Python
> 
>     def __init__(self, *args, **kwargs):
>         super(self.__class__, self).__init__(*args, **kwargs)
> ```

.
___
*[tests/pmemkv_tests.py, line 512 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYf8VsEJhcfB-yrVwa:-LuYf8VsEJhcfB-yrVwb:bl1mpyx) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/pmemkv_tests.py#L512)):*
> ```Python
>             temp = db2['1']
>         db1.stop()
>         db2.stop()
> ```

add whiteline
___
*[pmemkv/pmemkv.py, line 36 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYPf5YDQ7-6JMK5Rh1:-LuYeVWfC1SUHvGiKCWn:b9c95cq) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L36)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I'm not sure if those should  be inside Database(). It's possible that those values will be used for some other type (for example, in C/C++ config functions also return statuses - this is not the case for Python, but in future something could need those).
</blockquote></details>

I suppose that I agree with Igor.
___
*[pmemkv/pmemkv.py, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYfIEa2g48U4cBi9_w:-LuYfIEa2g48U4cBi9_x:bobes3u) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L88)):*
> ```Python
>             self.db.stop()
> 
>     # Puts the key/value pair into pmemkv datastore.
> ```

It may be not a part of this PR, but it's better to store function documentations in docstrings - e.g. they then might be used to generate a documentation file.

**Review by llugin — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor and @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @llugin)

___
*[tests/nontrivial_data_tests.py, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYc4_BCz9YPxCrweg-:-LuaUAQJ29Ddk079wdvB:b-7rcmyj) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L56)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

I would catch URLError first ( https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve ), then general Exception
</blockquote></details>

I cannot fully agree. I do not want to do any handling of such exception, just fail the test. In fact, best solution is to remove exception handling here and leave it to pytest.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, and @llugin)

___
*[pmemkv/kvengine.cc, line 32 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYMINZ4WdjzHq1yilQ:-LuaZwA49Ol3NCzAPSTw:bes9k5v) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L32)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What is it for? Maybe add some comment?
</blockquote></details>



It's commented in many places in python documentation: 

For all # variants of formats (s#, y#, etc.), the type of the length argument (int or Py_ssize_t) is controlled by defining the macro PY_SSIZE_T_CLEAN before including Python.h. If the macro was defined, length is a Py_ssize_t rather than an int. This behavior will change in a future Python version to only support Py_ssize_t and drop int support. It is best to always define PY_SSIZE_T_CLEAN.  
...

https://docs.python.org/3.7/c-api/arg.html 
___
*[pmemkv/kvengine.cc, line 76 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-Lua_cfA4xpEQcSDtK9U:-Lua_cfA4xpEQcSDtK9V:b-rkaixz) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L76)):*
> ```cpp
> pmemkv_NI_Start(PmemkvObject *self, PyObject* args) {
> 	Py_buffer engine, json_config;
> 	if (!PyArg_ParseTuple(args, "s*s*", &engine, &json_config)) {
> ```

@igchor
... We use such formats in places like this one.

**Review by llugin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/nontrivial_data_tests.py, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYc4_BCz9YPxCrweg-:-LubPpi_-J4qJ6zNR32y:b58jr62) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L56)):*
>In fact, best solution is to remove exception handling here and leave it to pytest.

Agreed. However, in current implementation the printed message may be a bit misleading (it may be perceived as connection error while for general Exception this may not be the case).

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: 0 of 10 files reviewed, 11 unresolved discussions (waiting on @igchor and @llugin)

___
*[tests/nontrivial_data_tests.py, line 41 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYWgr400LhAF0idtkz:-Luc2c5P2nu0J0Ae3_7_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L41)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

use single whitelines inside classes
</blockquote></details>

Done.
___
*[tests/nontrivial_data_tests.py, line 44 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYa0Ww2SRcTK-3WECC:-LubzvIE6g5BK03S4NYB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L44)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

>super(self.\_\_class\_\_, self)

I believe it's equivalent with just 'super() ' (with no arguments)
</blockquote></details>

Done.
___
*[tests/nontrivial_data_tests.py, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYc4_BCz9YPxCrweg-:-Lubz_jABrPZnkHMxsKT:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/nontrivial_data_tests.py#L56)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

>In fact, best solution is to remove exception handling here and leave it to pytest.

Agreed. However, in current implementation the printed message may be a bit misleading (it may be perceived as connection error while for general Exception this may not be the case).
</blockquote></details>

Done.
___
*[tests/pmemkv_tests.py, line 39 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYdAkDBpqE9CcFeQDT:-Luc0W6EENpTdyhjnkJd:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/pmemkv_tests.py#L39)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/pmemkv_tests.py, line 512 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYf8VsEJhcfB-yrVwa:-Luc0vO-5f6I_XFVzJil:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/tests/pmemkv_tests.py#L512)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

add whiteline
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 59 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYNSbu5FNwBZdAMNv7:-Lubf7SjBMOIoOmFAZWr:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why split declaration and assignment?
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 460 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYOfTp4_-sQ9QUBvAl:-Lubz34Y92nRY6QtHhPA:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/kvengine.cc#L460)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

wrong alignment?
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 36 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYPf5YDQ7-6JMK5Rh1:-LuaNfyP5CwOe3MXwVu2:b-l9z83w) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L36)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

I suppose that I agree with Igor.
</blockquote></details>

This patch was removed from this PR.
___
*[pmemkv/pmemkv.py, line 56 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYQUZ58gDs90zbuz4C:-Lubz4jx2MA6h42_lsfS:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We probably don't need __stopped variable anymore. We could implement stopped as checking whether db pointer is NULL (at the NI level)
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYfIEa2g48U4cBi9_w:-Luc2RrrAFBH2OjgS93m:b-upzm4) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L88)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

It may be not a part of this PR, but it's better to store function documentations in docstrings - e.g. they then might be used to generate a documentation file.
</blockquote></details>

It will be part of next PR
___
*[pmemkv/pmemkv.py, line 191 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LuYR7822sFm80S6RYOi:-Lubz6R4C7NINpHQrzbl:b-upzm4) ([raw file](https://github.com/pmem/pmemkv-python/blob/a35b4355e42189b4677d025ff3f0831574f08b09/pmemkv/pmemkv.py#L191)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

As we talked offline,  *_string_* functions should probably be removed. If not in this PR maybe at least create some issue?
</blockquote></details>

It will be part of next PR

**Review by llugin — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17#-:-Luc3e9589nJb13w83o5:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/pmemkv_tests.py, line 501 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LumcqWAAftCmdGqQd_z:-LumcqWAAftCmdGqQda-:b-e4at3t) ([raw file](https://github.com/pmem/pmemkv-python/blob/8893b458c17a4821954b4afe4591abf17f88248e/tests/pmemkv_tests.py#L501)):*
> ```Python
>         db.stop()
> 
>     def test_databases_interferation(self):
> ```

Interference

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor and @llugin)

___
*[tests/pmemkv_tests.py, line 501 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/17#-LumcqWAAftCmdGqQd_z:-LuqNlWDARZqpvFMXFQW:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/8893b458c17a4821954b4afe4591abf17f88248e/tests/pmemkv_tests.py#L501)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Interference
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/17#-:-LurXYEb4J3nhrUjEGTM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
