### PR TITLE
Add docs generating

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
It's missing exceptions/statuses, sphinx can't get its hands into that (pydoc on the other hand is able to display it for _pmemkv module).

preview: https://lukaszstolarczuk.github.io/pmemkv-python/v1.0/html/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)

### CODE REVIEW

**Review by szyrom — APPROVED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 84 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/40#-M0sbL-iB_nRHn91bHoJ:-M0sbL-j1t_ve-yfnDGt:bo3bsc6) ([raw file](https://github.com/pmem/pmemkv-python/blob/9b614588a80c112bb49d912ebaf8862dfa779d4b/utils/docker/images/Dockerfile.ubuntu-19.10#L84)):*
> ```
> RUN pip3 install pytest setuptools wheel
> #Install examples and docs dependencies
> RUN pip3 install falcon pexpect requests sphinx
> ```

Why would you install sphinx this way, rather than via apt dependencies?  That doesn't cover versions used by pretty much anyone on Debian/Ubuntu would.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @kilobyte and @szyrom)

___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 84 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/40#-M0sbL-iB_nRHn91bHoJ:-M0vGLBMBCKnFfzW05_F:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/9b614588a80c112bb49d912ebaf8862dfa779d4b/utils/docker/images/Dockerfile.ubuntu-19.10#L84)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Why would you install sphinx this way, rather than via apt dependencies?  That doesn't cover versions used by pretty much anyone on Debian/Ubuntu would.
</blockquote></details>

Done.

**Review by kilobyte — COMMENTED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @szyrom)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

___
*[doc/conf.py, line 12 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/40#-M0wIWJi4451E97FXU8p:-M0wIWJi4451E97FXU8q:bfp6ywd) ([raw file](https://github.com/pmem/pmemkv-python/blob/7dba95dbf4b0d715f78f36fb6425ff3f98fd5d70/doc/conf.py#L12)):*
> ```Python
> 
> # The short X.Y version
> version = '1.0'
> ```

do we need to hardcode this? I see you pass git describe output to sphinx already
___
*[doc/Makefile, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/40#-M0wIeBC8WpyO74PwZb9:-M0wIeBC8WpyO74PwZbA:b-q5oc01) ([raw file](https://github.com/pmem/pmemkv-python/blob/7dba95dbf4b0d715f78f36fb6425ff3f98fd5d70/doc/Makefile#L1)):*
> ```Makefile
> # Minimal makefile for Sphinx documentation
> ```

Some copyright?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @szyrom)

___
*[doc/conf.py, line 12 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/40#-M0wIWJi4451E97FXU8p:-M10fWPdECtNVkj8n6FB:b-lwz57l) ([raw file](https://github.com/pmem/pmemkv-python/blob/7dba95dbf4b0d715f78f36fb6425ff3f98fd5d70/doc/conf.py#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

do we need to hardcode this? I see you pass git describe output to sphinx already
</blockquote></details>

I don't think I can do this in an easy way. I could make some custom scripts, but I'm not sure if this is the right way...

(sry, I clicked the "resolve" button; not sure why that wasn't the "done" button :O )
___
*[doc/Makefile, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/40#-M0wIeBC8WpyO74PwZb9:-M10g8nu4Ee0MQDdDS4B:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/7dba95dbf4b0d715f78f36fb6425ff3f98fd5d70/doc/Makefile#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Some copyright?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r1, 1 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/40#-:-M15AQ0fCctvWjWF_9T9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
