### PR TITLE
Stop relying on undefined behaviour in tests

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/29)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/29)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/pmemkv_tests.py, line 464 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/29#-M-ngqdm8OlupejrF04g:-M-ngqdm8OlupejrF04h:b-k8nlkt) ([raw file](https://github.com/pmem/pmemkv-python/blob/da8cac5f75334bbfeb18fc3046aa1e8079c075e5/tests/pmemkv_tests.py#L464)):*
> ```Python
>         db.remove(key)
>         db[key] = "Some other string"
>         self.assertEqual(callback.result, "123".encode('utf-8'))
> ```

since you have var for "123" use it here, perhaps

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/29)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/pmemkv_tests.py, line 464 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/29#-M-ngqdm8OlupejrF04g:-M-o9BpjBWuFmv2BiRlF:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/da8cac5f75334bbfeb18fc3046aa1e8079c075e5/tests/pmemkv_tests.py#L464)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you have var for "123" use it here, perhaps
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/29#-:-M-oFU2p97L3nd0dcZCf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
