### PR TITLE
Make pmemkv buffer 1-dimensional

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/31)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/31)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[examples/basic_example.py, line 71 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/31#-M-njL9l5DehAKwFA8lO:-M-njL9m7vyuH_OVoOsm:b-w73mem) ([raw file](https://github.com/pmem/pmemkv-python/blob/d2630c08c7bd81920231b555793fcb8dee053f54/examples/basic_example.py#L71)):*
> ```Python
> )
> 
> print("Get first 2 bytes of value (without copying the entire value) and key in lambda expression")
> ```

of **the** value.. and **the** key in **a** lambda expression
___
*[examples/basic_example.py, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/31#-M-njRiSEfmBZCdHKWII:-M-njRiSEfmBZCdHKWIJ:bkmar31) ([raw file](https://github.com/pmem/pmemkv-python/blob/d2630c08c7bd81920231b555793fcb8dee053f54/examples/basic_example.py#L75)):*
> ```Python
>     key,
>     lambda v, k=key: print(
>         f"key: {k} with first 2 bytes of value: " f"{(memoryview(v)[0:2]).tobytes().decode()}"
> ```

the value

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/31)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[examples/basic_example.py, line 71 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/31#-M-njL9l5DehAKwFA8lO:-M-nmCxV2AktqAENXIoQ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/d2630c08c7bd81920231b555793fcb8dee053f54/examples/basic_example.py#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of **the** value.. and **the** key in **a** lambda expression
</blockquote></details>

Done.
___
*[examples/basic_example.py, line 75 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/31#-M-njRiSEfmBZCdHKWII:-M-nmIVs6yWPejijcGBE:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/d2630c08c7bd81920231b555793fcb8dee053f54/examples/basic_example.py#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the value
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/31#-:-M-oG4sh-muX1Ai1ql3c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
