### PR TITLE
Update Travis files

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
i.a.:
- update Ubuntu to 19.10
- add Fedora image (v. 31)
- remove memkind installation script
- enable both stable and current pmemkv's build

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.fedora-31, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtikeVe0i72FsA5oKL9:-LtikeVe0i72FsA5oKLA:b-ybw9lp) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.fedora-31#L39)):*
> ```
> # Pull base image
> FROM fedora:31
> MAINTAINER lukasz.stolarczuk@intel.com
> ```

szymon.romik
___
*[utils/docker/images/Dockerfile.fedora-31, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtikjAl3oX2gPMDVrDp:-LtikjAl3oX2gPMDVrDq:byhyz6n) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.fedora-31#L98)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> # Set required environment variables
> ENV OS fedora
> ENV OS_VER 31
> ENV PACKAGE_MANAGER rpm
> ENV NOTTY 1
> ```
</details>


please move it to the beginning
___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Ltil4c60tsycxUYftjs:-Ltil4c60tsycxUYftjt:bl8jlg4) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/install-libpmemobj-cpp.sh#L55)):*
> ```Shell
> elif [ "$1" = "RPM" ]; then
>       sudo rpm -i libpmemobj++*.rpm
> fi
> ```

else error out
___
*[utils/docker/images/install-pmdk.sh, line 51 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtilC55BfpJSV47DCiu:-LtilC55BfpJSV47DCiv:bl8jlg4) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/install-pmdk.sh#L51)):*
> ```Shell
>       sudo rpm -i rpm/*/libpmem-*.rpm
>       sudo rpm -i rpm/*/libpmemobj-*.rpm
> fi
> ```

else error out
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Ltikogk3UTYZlG2GYtx:-Ltikogk3UTYZlG2GYty:b-ybw9lp) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.ubuntu-19.10#L39)):*
> ```
> # Pull base image
> FROM ubuntu:19.10
> MAINTAINER lukasz.stolarczuk@intel.com
> ```

szymon.romik
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 95 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtikuDn9ppwEy0Q9a1F:-LtikuDn9ppwEy0Q9a1G:b-rmills) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.ubuntu-19.10#L95)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> # Set required environment variables
> ENV OS ubuntu
> ENV OS_VER 19.10
> ENV PACKAGE_MANAGER deb
> ENV NOTTY 1
> ```
</details>


please move it to the beginning

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.fedora-31, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtikeVe0i72FsA5oKL9:-Lu1fnxxEJikoGAGpVyR:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.fedora-31#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

szymon.romik
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-31, line 98 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtikjAl3oX2gPMDVrDp:-Lu1foFv2yLwQnKveguu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.fedora-31#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # Set required environment variables
> ENV OS fedora
> ENV OS_VER 31
> ENV PACKAGE_MANAGER rpm
> ENV NOTTY 1
> ```

please move it to the beginning
</blockquote></details>

Done.
___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Ltil4c60tsycxUYftjs:-Lu1fpb721kPC2-Aw3Vr:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/install-libpmemobj-cpp.sh#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

else error out
</blockquote></details>

Done.
___
*[utils/docker/images/install-pmdk.sh, line 51 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtilC55BfpJSV47DCiu:-Lu1fq0nCl_Df_ViHr3E:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/install-pmdk.sh#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

else error out
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Ltikogk3UTYZlG2GYtx:-Lu1fos_98WCKy9HAyXm:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.ubuntu-19.10#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

szymon.romik
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 95 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/16#-LtikuDn9ppwEy0Q9a1F:-Lu1fpC4DEuLzLpXMOJ0:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cc90f7fd76c2bac8564851d463ebc0826b536c8/utils/docker/images/Dockerfile.ubuntu-19.10#L95)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # Set required environment variables
> ENV OS ubuntu
> ENV OS_VER 19.10
> ENV PACKAGE_MANAGER deb
> ENV NOTTY 1
> ```

please move it to the beginning
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 57 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Lu2tBsM5Aj_aIEL08mr:-Lu2tBsM5Aj_aIEL08ms:b-g2hzm8) ([raw file](https://github.com/pmem/pmemkv-python/blob/e8fc4789b879ab21d303f5f048e795f1073ef148/utils/docker/images/install-libpmemobj-cpp.sh#L57)):*
> ```Shell
> 	make -j$(nproc) install
> else
> 	make -j$(nproc) package
> ```

`make -j$(nproc) package` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`
___
*[utils/docker/images/install-pmdk.sh, line 51 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Lu2t6xq9lkN02BV6Fsp:-Lu2t6xrD_B55oYpWjkQ:b-35zrao) ([raw file](https://github.com/pmem/pmemkv-python/blob/e8fc4789b879ab21d303f5f048e795f1073ef148/utils/docker/images/install-pmdk.sh#L51)):*
> ```Shell
> 	make -j$(nproc) install prefix=/usr
> else
> 	make -j$(nproc) BUILD_PACKAGE_CHECK=n $PACKAGE_TYPE
> ```

`make -j$(nproc) BUILD_PACKAGE_CHECK=n $PACKAGE_TYPE` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 57 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Lu2tBsM5Aj_aIEL08mr:-Lu81whu1FAor0HQIAJ_:bige1ak) ([raw file](https://github.com/pmem/pmemkv-python/blob/e8fc4789b879ab21d303f5f048e795f1073ef148/utils/docker/images/install-libpmemobj-cpp.sh#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`make -j$(nproc) package` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`
</blockquote></details>

as in ruby, I wouldn't change it, error with nice description would be given by cmake
___
*[utils/docker/images/install-pmdk.sh, line 51 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/16#-Lu2t6xq9lkN02BV6Fsp:-Lu8228V8A8127OlXV3n:b3kqx) ([raw file](https://github.com/pmem/pmemkv-python/blob/e8fc4789b879ab21d303f5f048e795f1073ef148/utils/docker/images/install-pmdk.sh#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`make -j$(nproc) BUILD_PACKAGE_CHECK=n $PACKAGE_TYPE` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16#-:-Lu83WmS1uIEtyD2N-MW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
