### PR TITLE
add docs content to gh-pages

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
preview: https://lukaszstolarczuk.github.io/pmemkv-python

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/41)

### CODE REVIEW

**Review by szyrom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/41)* status: 1 of 29 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[index.md, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/41#-M0rUxjSBPqdw57THuei:-M0rUxjSBPqdw57THuej:b-l8di33) ([raw file](https://github.com/pmem/pmemkv-python/blob/f3922f1f1153045a689ab23176e054d02f5cd5be/index.md#L9)):*
> ```Markdown
> 
> **pmemkv** is a local/embedded key-value datastore optimized for persistent memory.
> The latest python bindings release was 1.0 - it is functionally equivalent to libpmemkv 1.0.
> ```

s/was/is

**Comment by szyrom** [comment]
do we need to have all this code in our repo (including binary files)? can we include this somehow?

**Review by lukaszstolarczuk — COMMENTED** [review]
@szyrom we could try to include these files somehow, but I'm not sure if this is worth it. If we put some external links they could become outdated. We generate these files using sphinx, so if they change anything we'll have to adjust our gh-pages content...

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/41#-:-M0vSu1oAmKa_7oKhRwN:bs08598)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @szyrom)

___
*[index.md, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/41#-M0rUxjSBPqdw57THuei:-M0vStKv9nzk1WLRInhf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/f3922f1f1153045a689ab23176e054d02f5cd5be/index.md#L9)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

s/was/is
</blockquote></details>

Done.

**Review by szyrom — COMMENTED** [review]
please use pmemkv-python instead of pmemkv where applicable 

> Reviewed 2 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/41#-:-M0v_GxZ0_JuV7ebfYWD:b24jpbm)* status: 2 of 30 files reviewed, all discussions resolved (waiting on @szyrom)

**Comment by lukaszstolarczuk** [comment]
> please use pmemkv-python instead of pmemkv where applicable
> 
> > Reviewed 2 of 29 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/41#-:-M0v_GxZ0_JuV7ebfYWD:b24jpbm)_ status: 2 of 30 files reviewed, all discussions resolved (waiting on @szyrom)

done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 81 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/41#-:-M15BEN94sychyEXyV0r:bnfp4nl)* status: 1 of 76 files reviewed, all discussions resolved (waiting on @szyrom)

**Pull request merged**
