### PR TITLE
Return values small fixes

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/35)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/35)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[pmemkv/kvengine.cc, line 655 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/35#-M-xajgT-dKhmsJyK04I:-M-xajgT-dKhmsJyK04J:bapndo3) ([raw file](https://github.com/pmem/pmemkv-python/blob/d4b03fef7e6e2b9bb9596318ff21ab836022e18f/pmemkv/kvengine.cc#L655)):*
> ```cpp
> 	{NULL, NULL, 0, NULL}};
> 
> static PyTypeObject PmemkvType = {
> ```

can you please add a short comment, what this piece of code does..?

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/35#-:-M-yBgy66KhKe4n3WTiv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/35)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[pmemkv/kvengine.cc, line 655 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/35#-M-xajgT-dKhmsJyK04I:-M-z-8qL1mIiJM3rUr7D:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/d4b03fef7e6e2b9bb9596318ff21ab836022e18f/pmemkv/kvengine.cc#L655)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you please add a short comment, what this piece of code does..?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/35)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/35#-:-M01t79bAipDYYnq8pUC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
