### PR TITLE
Replace PMEMKV_STATUS_FAILED with PMEMKV_STATUS_UNKNOWN_ERROR

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)

### CODE REVIEW

**Comment by ldorau** [comment]
@lukaszstolarczuk @igchor please review

**Review by igchor — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[pmemkv.py, line 246 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/9#-LpSjFmsCIHTIiZWB4yr:-LpSjFmtAPdUNEe3I9Kl:b3060ys) ([raw file](https://github.com/pmem/pmemkv-python/blob/fa3985c27a020320dd1655d5971888f7a40cd1df/pmemkv.py#L246)):*
> ```Python
>         value = pmemkv_NI.get(key)
>         # XXX fix the case: value == int(PMEMKV_STATUS_UNKNOWN_ERROR)
>         if value == PMEMKV_STATUS_UNKNOWN_ERROR:
> ```

why only checking return value equals to UNKNOWN_ERROR, not similarly to e.g. ruby binding, like:
"value != PMEMKV_STATUS_OK && value != PMEMKV_STATUS_NOT_FOUND" ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[pmemkv.py, line 246 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/9#-LpSjFmsCIHTIiZWB4yr:-LpSmUMz8fPAngue1aNJ:b2et774) ([raw file](https://github.com/pmem/pmemkv-python/blob/fa3985c27a020320dd1655d5971888f7a40cd1df/pmemkv.py#L246)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why only checking return value equals to UNKNOWN_ERROR, not similarly to e.g. ruby binding, like:
"value != PMEMKV_STATUS_OK && value != PMEMKV_STATUS_NOT_FOUND" ?
</blockquote></details>

Because it fails when get() returns a correct data too.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[pmemkv.py, line 246 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/9#-LpSjFmsCIHTIiZWB4yr:-LpT54SYAyvC3tDygQxT:btxf8bp) ([raw file](https://github.com/pmem/pmemkv-python/blob/fa3985c27a020320dd1655d5971888f7a40cd1df/pmemkv.py#L246)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because it fails when get() returns a correct data too.
</blockquote></details>

perhaps "pmemkv_NI_Get" in kvengine.cc should also be fixed...?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[pmemkv.py, line 246 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/9#-LpSjFmsCIHTIiZWB4yr:-LpT5JN46IHap4_J4gHA:b-6ucdw6) ([raw file](https://github.com/pmem/pmemkv-python/blob/fa3985c27a020320dd1655d5971888f7a40cd1df/pmemkv.py#L246)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps "pmemkv_NI_Get" in kvengine.cc should also be fixed...?
</blockquote></details>

Yes, but not now, later.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[pmemkv.py, line 246 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/9#-LpSjFmsCIHTIiZWB4yr:-LpTLTat0SJ89I044jDi:bhjh9mf) ([raw file](https://github.com/pmem/pmemkv-python/blob/fa3985c27a020320dd1655d5971888f7a40cd1df/pmemkv.py#L246)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, but not now, later.
</blockquote></details>

It was discussed with @igchor offline

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/9#-:-LpTRMjZDxLDoaPnyyz4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[pmemkv.py, line 246 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/9#-LpSjFmsCIHTIiZWB4yr:-LpTR9Vz0FErJ2gA7vkj:bdm58hb) ([raw file](https://github.com/pmem/pmemkv-python/blob/fa3985c27a020320dd1655d5971888f7a40cd1df/pmemkv.py#L246)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It was discussed with @igchor offline
</blockquote></details>

ok, then it works for me :)
please file an issue, so we won't forget

**Pull request merged**
