### PR TITLE
Remove unused parameters from PyTypeObject definitions 

### PR DESCRIPTION
**Pull request by karczex**
It's needed due to change of name unused variable tp_print to
tp_vectorcall_offset in PEP590.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/39)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/39)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
Hm, maybe we could stay with designated initializers but only initialize the members we care about (and skip the ones which are 0)? The order and name of the variables we care about cannot change, right?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/39#-:-M0HN0Yu9WwQlKYaCCSx:b-c7h0gh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
@igchor I suppose it cannot... however PEP590 shows that, in some special situations it can. Anyhow, I done it as you suggested. 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/39#-:-M0HtVbe6xGmWebgMdz1:b19gou5)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/39#-:-M0HutBLD5_mhIXWglM6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
