### PR TITLE
Implementation of KVEngine.cc Pmemkv.py APIs

### PR DESCRIPTION
**Pull request by Kalyanvangipurapu**
PR for Python bindings for Pmemkv.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
Please provide instructions and scripts to build this.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1#-:-Lg2l2PE8yvYS_S2KZ7v:b-ect117)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Kalyanvangipurapu)

___
*[kvengine.cc, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LfyYEYB9rEOWhrN8AmM:-LfyYEYB9rEOWhrN8AmN:b-w6di97) ([raw file](https://github.com/pmem/pmemkv-python/blob/992586c3b14f92a0f62d2163bb7f6968c5e5aaac/kvengine.cc#L3)):*
> ```cpp
> #include <Python.h>
> #include <string>
> #include "kvengine.h"
> ```

Please provide this file in this PR. (make sure the code compiles).

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Kalyanvangipurapu)

___
*[kvengine.cc, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/1#-Lg7Ioj73y_u2WYseGeA:-Lg7Ioj73y_u2WYseGeB:b8972j7) ([raw file](https://github.com/pmem/pmemkv-python/blob/992586c3b14f92a0f62d2163bb7f6968c5e5aaac/kvengine.cc#L14)):*
> ```cpp
> 	Py_buffer engine, path;
> 	if (!PyArg_ParseTuple(args, "s*s*", &engine, &path)) {
>                 return NULL;
> ```

Please apply some unified code formatting. Some indentations are improper (at best apply tabs not spaces)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Kalyanvangipurapu)

___
*[kvengine.cc, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LfyYEYB9rEOWhrN8AmM:-LgCWwWM1WI1ELNf5r4_:b-3atb8h) ([raw file](https://github.com/pmem/pmemkv-python/blob/992586c3b14f92a0f62d2163bb7f6968c5e5aaac/kvengine.cc#L3)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please provide this file in this PR. (make sure the code compiles).
</blockquote></details>

I requested adding this file in PR because I thought this file is specific for Python.

To include header with C API use:
#include <libpmemkv.h>

and remove kvengine.h from PR

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @Kalyanvangipurapu)

___
*[pmemkv.py, line 35 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LgY8raI0l3GCupq2TJW:-LgY8raI0l3GCupq2TJX:b-5sagg7) ([raw file](https://github.com/pmem/pmemkv-python/blob/f408b89ecb56ae7972838de28460c9be6dcda821/pmemkv.py#L35)):*
> ```Python
> import pmemkv_NI
> 
> class KVEngine():
> ```

Please describe each method (what parameters is takes and what is return value)
___
*[pmemkv.py, line 37 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LgY8g0V9Cn9jbrHplGD:-LgY8g0V9Cn9jbrHplGE:b1pqgfw) ([raw file](https://github.com/pmem/pmemkv-python/blob/f408b89ecb56ae7972838de28460c9be6dcda821/pmemkv.py#L37)):*
> ```Python
> class KVEngine():
> 
>     stopped = False
> ```

I think it would be better to hide "stopped" to kvengine.cc (check if engine stopped in pmemkv_NI.stop())
___
*[setup.py, line 36 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LgY8A0s5X4VcrYSwpId:-LgY8A0t-iZajtDdGlRy:bhzyl8k) ([raw file](https://github.com/pmem/pmemkv-python/blob/f408b89ecb56ae7972838de28460c9be6dcda821/setup.py#L36)):*
> ```Python
> import os
> 
> link_modules = Extension("pmemkv_NI", ["kvengine.cc"], extra_objects = ["/usr/local/lib/libpmemkv.so"])
> ```

Please do not hard-code path to library. I'm not an expert in this but maybe you could use config files?
https://docs.python.org/2/distutils/configfile.html

**Comment by Kalyanvangipurapu** [comment]
Ruby has been declared a variable 'stopped' in KVEngine class and we followed the same as we are doing porting from ruby to python. Below is the ruby KVEngine class

	class KVEngine  
    	   def initialize(engine, json_string)
   	   @stopped = false 

We can implement your comment here but the problem is  while checking, whether the engine is stopped or not, after stop method is called from the test case like below

67   it 'stops engine multiple times' do 
68     kv = KVEngine.new(ENGINE, CONFIG) 
69     expect(kv.stopped?).to be false 
70     kv.stop 
71     expect(kv.stopped?).to be true 
72     kv.stop 
73     expect(kv.stopped?).to be true 
74     kv.stop 
75     expect(kv.stopped?).to be true 
76   end 

After stop method call from above, we are verifying the 'stopped' member(expect(kv.stopped?).to be true) to make sure the engine is stopped.

If we move this 'stopped' variable to pmemkv_NI then we have to implement one more method in both Python KVEngine Class and also pmemkv_NI for test cases to verify like below

def is_engine_stopped(self):  // Python KVEngine
	return bool(pmemkv_NI.is_engine_stopped())

static PyObject*   // pmemkv_NI
pmemkv_NI_is_engine_stopped(self) {
	return kv == nullptr ? true : false;
}|

please let us know your views on this issue

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: all files reviewed, 4 unresolved discussions (waiting on @Kalyanvangipurapu)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @igchor and @Kalyanvangipurapu)

___
*[pmemkv.py, line 37 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LgY8g0V9Cn9jbrHplGD:-LglYFSC0-QvsPNWz-Zk:b-yyybsk) ([raw file](https://github.com/pmem/pmemkv-python/blob/f408b89ecb56ae7972838de28460c9be6dcda821/pmemkv.py#L37)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it would be better to hide "stopped" to kvengine.cc (check if engine stopped in pmemkv_NI.stop())
</blockquote></details>

Okay, I missed that ruby exposes the variable in the same way - It's ok then.
___
*[pmemkv.py, line 38 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LglYWHKBTboI2nuiCwV:-LglYWHKBTboI2nuiCwW:buya5jj) ([raw file](https://github.com/pmem/pmemkv-python/blob/1447519c47b4b7aedffd1b2e4bf2e8ef48133f81/pmemkv.py#L38)):*
> ```Python
> 
>     stopped = False
>     # Starts the given engine with the help of pmemkv_NI_Start API 
> ```

I don't think writing about pmemkv_NI methods is necessary. Comment like "Start the given engine. Takes engine name and configuration from the end user. " is enough. Please also remove mentions of pmemkv_NI in other desriptions.
___
*[pmemkv.py, line 38 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LglitGcBRrEJr16-KPR:-LglitGcBRrEJr16-KPS:by483bv) ([raw file](https://github.com/pmem/pmemkv-python/blob/1447519c47b4b7aedffd1b2e4bf2e8ef48133f81/pmemkv.py#L38)):*
> ```Python
> 
>     stopped = False
>     # Starts the given engine with the help of pmemkv_NI_Start API 
> ```

Please remove whitespaces at the end of commets
___
*[pmemkv.py, line 57 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LglZCil--uWFT0k-y9C:-LglZCim-miqBSQEOuQ0:bih1itn) ([raw file](https://github.com/pmem/pmemkv-python/blob/1447519c47b4b7aedffd1b2e4bf2e8ef48133f81/pmemkv.py#L57)):*
> ```Python
>         if retVal < 0:
>             raise RuntimeError("Unable to put " +str(key))
>         return bool(retVal)
> ```

I think you should not return status here. If put succeeds return nothing, if it fails throw an expection (I believe in ruby we do not return status in put).
___
*[pmemkv.py, line 60 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LglZXQR1E8fw2ANUhJE:-LglZXQR1E8fw2ANUhJF:b-oy8yjq) ([raw file](https://github.com/pmem/pmemkv-python/blob/1447519c47b4b7aedffd1b2e4bf2e8ef48133f81/pmemkv.py#L60)):*
> ```Python
> 
>     # Gets the value for the given key from pmemkv datastore with the help of pmemkv_NI_Get API
>     # Takes key from the end user and returns the value  
> ```

That's not true, get returns status not value.

**Comment by Kalyanvangipurapu** [comment]
To install the last update use:
sudo PMEMKV_SHARED_LIB=/usr/local/lib/libpmemkv.so python3.7 setup.py install

**Comment by Kalyanvangipurapu** [comment]
As per the Ruby's source code, get method is taking key as parameter and returning the value not status.

```ruby
def get(key)
	result = nil
	callback = lambda do |context, valuebytes, value|
	  result = value.get_bytes(0, valuebytes)
	end
	Pmemkv.kvengine_get(@kv, nil, key.bytesize, key, callback)
	result
end
```

**Review by igchor — COMMENTED** [review]
When you respond to comments please do this through Reviewable (https://reviewable.io/reviews/pmem/pmemkv-python/1). Write the response to the according comment instead of making a global reply.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1#-:-LhB9Yj6CDSWE1yyEciL:blmgbtq)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor and @Kalyanvangipurapu)

___
*[setup.py, line 36 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/1#-LgY8A0s5X4VcrYSwpId:-LhB8HRa3qegc1iBUVnD:bl13qwb) ([raw file](https://github.com/pmem/pmemkv-python/blob/f408b89ecb56ae7972838de28460c9be6dcda821/setup.py#L36)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please do not hard-code path to library. I'm not an expert in this but maybe you could use config files?
https://docs.python.org/2/distutils/configfile.html
</blockquote></details>

After a bit of research, I found a proper way, you should not use extra_object at all, instead you should have:
`link_modules = Extension("pmemkv_NI", ["kvengine.cc"], libraries = ["pmemkv"])`

And then, if pmemkv is installed in defualt directory (e.g. /usr) following is enough:

`sudo python3 setup.py install`

If pmemkv is in some other place user must do following:
`python3 setup.py build_ext --library-dirs=path_to_pmemkv_lib_dir --include-dirs=path_to_pmemkv_include_dir`
`sudo python3 setup.py install`

Please change setup.py in the way I proposed and update documentation (decribe what I have written above).

**Comment by szyrom** [comment]
@Kalyanvangipurapu can you adjust class name(KVEngine->Database) to match more suitable and similar to recently-merged change in ruby bindings repo ? https://github.com/pmem/pmemkv-ruby/commit/403ab8d6e6cde7c36f62fc0b94df14ddea829369

**Review by igchor — COMMENTED** [review]
:lgtm: Just please change "stop" method to "close" (as in ruby bindings).

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1#-:-LhZvqNA18xVpJn2qXAM:b-yxvk7z)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @Kalyanvangipurapu)

**Review by Kalyanvangipurapu — COMMENTED** [review]
We still see that in ruby, "stop" method is not changed.
 ```ruby
def stop
    unless @stopped
      @stopped = true
      Pmemkv.pmemkv_close(@db)
    end
  end
```

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1#-:-LhdG7E81SD2VxAKzyUp:bz9s85e)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @Kalyanvangipurapu)

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1#-:-LhdMnfR-svZDfbKo2Ju:bnfp4nl)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @Kalyanvangipurapu)

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 3 files at r10, 2 of 4 files at r11, 3 of 3 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor and @Kalyanvangipurapu)

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/1)* status: all files reviewed, 1 unresolved discussion (waiting on @Kalyanvangipurapu)

**Comment by szyrom** [comment]
@igchor @lukaszstolarczuk merge?

**Pull request merged**
