### PR TITLE
Make config dictionary instead of raw string

### PR DESCRIPTION
**Pull request by karczex**
This approach is more flexible and less error prone.
* There is no way, that user create malformed config, as dictionary is
  part of python syntax
* There is no need to escape quotes, which may be confusing
* There is easy way to import config from file (like in example)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[examples/basic_example.py, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/21#-LyF4BHDD8y2ULfD1pXB:-LyF4BHDD8y2ULfD1pXC:b-a3ms0x) ([raw file](https://github.com/pmem/pmemkv-python/blob/90473a27977344eeb89afa891d42e8d095b63ca5/examples/basic_example.py#L15)):*
> ```Python
> 
> print("Starting engine")
> db = pmemkv.Database("vsmap", config)
> ```

please also add example with json object not loaded from file (just convert previous string json into json object).

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21#-:-LySqRof688OeFPYAHCq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[examples/basic_example.py, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/21#-LyTD96y95WKMNrJDFPR:-LyTD96y95WKMNrJDFPS:bklt6qe) ([raw file](https://github.com/pmem/pmemkv-python/blob/01931ddbbfba8f2e3fe0a5560d35e74430713455/examples/basic_example.py#L1)):*
> ```Python
> import pmemkv
> ```

there's no license in this file?

please also check other files (fix if any, not necessarily in this PR)
___
*[pmemkv/pmemkv.py, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/21#-LyTDVKm4rhoxdf_g7g6:-LyTDVKm4rhoxdf_g7g7:b-4s0rqb) ([raw file](https://github.com/pmem/pmemkv-python/blob/90473a27977344eeb89afa891d42e8d095b63ca5/pmemkv/pmemkv.py#L40)):*
> ```Python
>     def __init__(self, engine, config):
>         if not isinstance(config, dict):
>             raise TypeError("Config shuld be dictionary")
> ```

should, misspell

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @igchor, @ldorau, and @lukaszstolarczuk)

___
*[examples/basic_example.py, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/21#-LyTD96y95WKMNrJDFPR:-LyTvJJF-HtkDrkKkIFs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/01931ddbbfba8f2e3fe0a5560d35e74430713455/examples/basic_example.py#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there's no license in this file?

please also check other files (fix if any, not necessarily in this PR)
</blockquote></details>

Done.
___
*[examples/basic_example.py, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/21#-LyF4BHDD8y2ULfD1pXB:-LyTvM96AaxFfqLYuMtE:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/90473a27977344eeb89afa891d42e8d095b63ca5/examples/basic_example.py#L15)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please also add example with json object not loaded from file (just convert previous string json into json object).
</blockquote></details>

Done.
___
*[pmemkv/pmemkv.py, line 40 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/21#-LyTDVKm4rhoxdf_g7g6:-LyTvNL8C0cl5m_x9Yfm:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/90473a27977344eeb89afa891d42e8d095b63ca5/pmemkv/pmemkv.py#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should, misspell
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21#-:-LyUL6SKAYG3mfg_T9z7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/21#-:-LyZR4IR4b4-bLUBrpaC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
