### PR TITLE
Add Travis

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/8)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/8)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfnpS8RaSze9UObIZ:-LpCfnpS8RaSze9UObI_:bpp6stj) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L43)):*
> ```Shell
> 
> # build and install pmemkv
> cd ~
> ```

not needed
___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfClQAcPbv4BtbvU4:-LpCfClR17GQLubxAIje:b-6rzh6t) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L55)):*
> ```Shell
> echo
> echo "####################################################################"
> echo "### Verifying building and installing of the pmemkv-python bindings "
> ```

similarly to nodejs, perhaps:
echo "### Verifying building, installation and tests execution"

and then move testing here, leaving only example down below 
___
*[utils/docker/run-build.sh, line 65 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfNuq0eLNsd2Ie_k3:-LpCfNuq0eLNsd2Ie_k4:b-eilcik) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L65)):*
> ```Shell
> echo "################################################################"
> cd $WORKDIR
> cd tests
> ```

make it absolute path, please
___
*[utils/docker/run-build.sh, line 67 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfQl13IsrCWFuRvTx:-LpCfQl13IsrCWFuRvTy:b3kqx) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L67)):*
> ```Shell
> cd tests
> python3 -m unittest -v pmemkv_tests.py
> cd ../examples
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/8)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfnpS8RaSze9UObIZ:-LpCxWFw5d75nICA9lnX:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfClQAcPbv4BtbvU4:-LpCxs4y5weYLGAr70l_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

similarly to nodejs, perhaps:
echo "### Verifying building, installation and tests execution"

and then move testing here, leaving only example down below 
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 65 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfNuq0eLNsd2Ie_k3:-LpCy6zT0aPU0CoIQp3D:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make it absolute path, please
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 67 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/8#-LpCfQl13IsrCWFuRvTx:-LpCy7MTDja0WJ70u-Q1:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/fc427772d81d0f42379431f256bd755776d38c4a/utils/docker/run-build.sh#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/8#-:-LpDGPQ04y1RqAfjKA_s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/8#-:-LpD_JbT18B_OfWQtkCF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
