### PR TITLE
Handle allocation failures in callbacks

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/34)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/34)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[pmemkv/kvengine.cc, line 296 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xl2AS-0YWIRAaeKjG:-M-xl2AS-0YWIRAaeKjH:b-nxn7pf) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L296)):*
> ```cpp
> 		return;
> 	}
> 	// PyTuple_SetItem sets exception on failure on it's own
> ```

it's -> its
___
*[pmemkv/kvengine.cc, line 296 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xnks0Bd17_3_wutbl:-M-xnks13hNMmson1SFl:bct4i3l) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L296)):*
> ```cpp
> 		return;
> 	}
> 	// PyTuple_SetItem sets exception on failure on it's own
> ```

an exception
___
*[pmemkv/kvengine.cc, line 301 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xnbfc0nIt8_xoSiXS:-M-xnbfd9QRqtskfQ6qO:b-957pt1) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L301)):*
> ```cpp
> 		Py_XDECREF(res);
> 	}
> 	Py_XDECREF(args); // args is owner of entry reference counter
> ```

the owner of the entry
___
*[pmemkv/kvengine.cc, line 338 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xpkPV26eJPsp2IVdz:-M-xpkPV26eJPsp2IVe-:b-5ch2yx) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L338)):*
> ```cpp
> 		return -1;
> 	}
> 	if ((PyTuple_SetItem(args, 0, (PyObject *)key_buffer) == 0) &&
> ```

you can put the same comment about an exception thrown on its own here

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/34)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex)

___
*[pmemkv/kvengine.cc, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-yC-9J1s2jQnEp7gW_:-M-yC-9KDT6TywRts-no:bwwwinv) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L42)):*
> ```cpp
> #include <unordered_map>
> 
> #define PY_MEMORY_EXCEPTION                                                              \
> ```

why macro and not just a function?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/34)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[pmemkv/kvengine.cc, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-yC-9J1s2jQnEp7gW_:-M-yvFfW7beXzqHYPGES:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L42)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why macro and not just a function?
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 296 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xl2AS-0YWIRAaeKjG:-M-yvPl68lZQp_jYZH9_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L296)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's -> its
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 296 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xnks0Bd17_3_wutbl:-M-yvPap-68LWsLb-vGd:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L296)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

an exception
</blockquote></details>

Done.
___
*[pmemkv/kvengine.cc, line 338 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xpkPV26eJPsp2IVdz:-M-yvFA0ABy2WkHPlo7J:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L338)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can put the same comment about an exception thrown on its own here
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/34)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[pmemkv/kvengine.cc, line 301 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/34#-M-xnbfc0nIt8_xoSiXS:-M-ywDiHAQ-lKhz3TLMX:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/4cb69944cf166f35b11a2f3f37cda3aef25e8f6b/pmemkv/kvengine.cc#L301)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the owner of the entry
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/34#-:-M-ywQIPCK2uVNFr14XL:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

**Pull request merged**
