### PR TITLE
Rest api example

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[examples/restAPI/pmemkvREST.py, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F-Ugv2zUu-3dyHv_d:-M-F-Ugv2zUu-3dyHv_e:bjou5ym) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/pmemkvREST.py#L15)):*
> ```Python
>             config = {"path" : os.environ['TEST_PATH']}
>         except KeyError:
>             print("Please configure path")
> ```

"please configure path"? it's not very descriptive message, I, personally, wouldn't know what's wrong
___
*[examples/restAPI/run_example.sh, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F0m8U-52itDz22Gv_:-M-F0m8U-52itDz22Gva:br4dpqv) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/run_example.sh#L10)):*
> ```Shell
> 	if [ "${1}" != "${2}" ]
> 	then
> 		echo ""Assertion failed:  \"$1\" not equal"\"$2\""
> ```

double `""` at the beginning
___
*[examples/restAPI/run_example.sh, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F0VS11y7QQCfREWrI:-M-F0VS11y7QQCfREWrJ:b-e60wxr) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/run_example.sh#L34)):*
> ```Shell
> 	pmempool create -s 1073741824 obj -l pmemkv ${TEST_PATH}
> fi
> echo "Run server with pmemkv concurrent hash map as storage"
> ```

"pmemkv concurrent hash map" ?
___
*[utils/docker/images/install-pmdk.sh, line 56 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F-9P0DmZ3WZ0Npjnh:-M-F-9P171ovuzYoUOoB:bkm5see) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/utils/docker/images/install-pmdk.sh#L56)):*
> ```Shell
> 		sudo dpkg -i dpkg/libpmem_*.deb dpkg/libpmem-dev_*.deb
> 		sudo dpkg -i dpkg/libpmemobj_*.deb dpkg/libpmemobj-dev_*.deb
> 		sudo dpkg -i dpkg/pmreorder_*.deb
> ```

is it needed?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @karczex)

___
*[examples/restAPI/run_example.sh, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F0uWn2Nd9DQzzn5wt:-M-F0uWn2Nd9DQzzn5wu:b1lihds) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/run_example.sh#L32)):*
> ```Shell
> if [ ! -f ${TEST_PATH} ]; then
> 	echo "Creating pool for pmemkv"
> 	pmempool create -s 1073741824 obj -l pmemkv ${TEST_PATH}
> ```

maybe make this magic number a const, defined on top of the file

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @karczex)

___
*[examples/restAPI/pmemkvREST.py, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ngumX2ZwvBQ5uIa7U:-M-ngumX2ZwvBQ5uIa7V:b6htgd) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/pmemkvREST.py#L58)):*
> ```Python
>             """
>             self.db = pmemkv.Database("cmap", config)
>         except pmemkv.Error as e:
> ```

Is pmemkv.Error a base class for all the exceptions? 
___
*[examples/restAPI/run_example.py, line 12 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-nhBbMDFjvLF2Rx4TI:-M-nhBbMDFjvLF2Rx4TJ:br4z8lp) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/run_example.py#L12)):*
> ```Python
> 
>     def run(self):
>         self.server = pexpect.spawn("/usr/bin/python3 pmemkvREST.py", env={"PMEMKV_POOL_PATH" : self.pool_path}, cwd=self.script_dir)
> ```

please do not hardcode paths to python, can'y you jus import appropriate function from pmemkvREST and call it in separate process?
___
*[examples/restAPI/run_example.py, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-nhU-cCEgYhfGIn76W:-M-nhU-cCEgYhfGIn76X:b7ti21k) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/run_example.py#L27)):*
> ```Python
> 
> if __name__ == "__main__":
>     pool_path = os.environ.get("TEST_PATH") or "/dev/shm/pmemkvREST_pool"
> ```

TEST_PATH? wasn't it suppose to be PMEMKV_POOL_PATH?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @karczex)

___
*[examples/restAPI/run_example.py, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-nkmM39_ZdhA8IQkj0:-M-nkmM39_ZdhA8IQkj1:bsvggxu) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/run_example.py#L1)):*
> ```Python
> import pexpect
> ```

License missing

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[examples/restAPI/pmemkvREST.py, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F-Ugv2zUu-3dyHv_d:-M-oHn9yEnVjnDDKuKc-:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/pmemkvREST.py#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"please configure path"? it's not very descriptive message, I, personally, wouldn't know what's wrong
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ngumX2ZwvBQ5uIa7U:-M-nmEoL7-x4YAbIgMsf:b2nign6) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/pmemkvREST.py#L58)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is pmemkv.Error a base class for all the exceptions? 
</blockquote></details>

yes
___
*[examples/restAPI/run_example.py, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-nkmM39_ZdhA8IQkj0:-M-oIbFvDpYfoE08LF3O:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/run_example.py#L1)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

License missing
</blockquote></details>

Done.
___
*[examples/restAPI/run_example.py, line 12 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-nhBbMDFjvLF2Rx4TI:-M-oQoeXCe_TTM2Be9_U:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/run_example.py#L12)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please do not hardcode paths to python, can'y you jus import appropriate function from pmemkvREST and call it in separate process?
</blockquote></details>

Done.
___
*[examples/restAPI/run_example.py, line 27 at r2](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-nhU-cCEgYhfGIn76W:-M-oRGeK0kGSs35tZcTd:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/f402d166c9ada6eeaea42c06df2d82848c26a728/examples/restAPI/run_example.py#L27)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

TEST_PATH? wasn't it suppose to be PMEMKV_POOL_PATH?
</blockquote></details>

Done.
___
*[examples/restAPI/run_example.sh, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F0m8U-52itDz22Gv_:-M-oShGG8YlSnQ08wHxK:bhgc2kx) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/run_example.sh#L10)):*
> removed
___
*[examples/restAPI/run_example.sh, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F0uWn2Nd9DQzzn5wt:-M-oSiv81rRcH2P7azP6:b-hfpv0l) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/run_example.sh#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe make this magic number a const, defined on top of the file
</blockquote></details>

removed
___
*[examples/restAPI/run_example.sh, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F0VS11y7QQCfREWrI:-M-oSfTc7-fk_jR2Mqrv:b-hfpv0l) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/examples/restAPI/run_example.sh#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"pmemkv concurrent hash map" ?
</blockquote></details>

removed
___
*[utils/docker/images/install-pmdk.sh, line 56 at r1](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-F-9P0DmZ3WZ0Npjnh:-M-oSVSW7wNehvj70wME:b-5hcj1a) ([raw file](https://github.com/pmem/pmemkv-python/blob/d7fea1f8d545bfda7e73e3f297db41dbcd69ac47/utils/docker/images/install-pmdk.sh#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it needed?
</blockquote></details>

libpmemobj is pmempool dependency

**Review by igchor — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[examples/restAPI/pmemkvREST.py, line 3 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oUqYEDLCIzW7X-yBq:-M-oUqYFDNZ5mKz5uhZS:b-f7s2z9) ([raw file](https://github.com/pmem/pmemkv-python/blob/e34743eaa556d86505cf9ba88b5b72396cc5b394/examples/restAPI/pmemkvREST.py#L3)):*
> ```Python
> #!/usr/bin/env python3
> 
> #  Copyright 2019-2020, Intel Corporation
> ```

shouldn't it be just 2020
___
*[examples/restAPI/run_example.py, line 3 at r3](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oUtko0EuCzG_WyqwL:-M-oUtko0EuCzG_WyqwM:b-8k884i) ([raw file](https://github.com/pmem/pmemkv-python/blob/e34743eaa556d86505cf9ba88b5b72396cc5b394/examples/restAPI/run_example.py#L3)):*
> ```Python
> #!/usr/bin/env python3
> 
> #  Copyright 2019-2020, Intel Corporation
> ```

2020?

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: all files reviewed, 12 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ol6TN5pGpriJ-fCLW:-M-ol6TN5pGpriJ-fCLX:bivs96f) (no related file):*
please update the "Examples" section in top-level README.md

---
___
*[examples/restAPI/pmemkvREST.py, line 34 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oi_6UD9G5wNwwNe-G:-M-oi_6V01LhaQC-w-RQ:b-ba0kn5) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L34)):*
> ```Python
> 
> """ This example shows how to use pmemkv-python binding as data store backend for
> simple REST API service based on falcon framework  """
> ```

double space at the end of the sentence -> replace this with '. '
___
*[examples/restAPI/pmemkvREST.py, line 77 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oh_LH-8uNQ3sqBpbK:-M-oh_LI5Ri9wbwShpZY:bjcq5ea) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L77)):*
> ```Python
>         print(req)
>         """
>         Pass callback function, which is run on every key in datastore.
> ```

in the datastore
___
*[examples/restAPI/pmemkvREST.py, line 78 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oiGUP9fhj6YTCEEvJ:-M-oiGUP9fhj6YTCEEvK:blgkjcb) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L78)):*
> ```Python
>         """
>         Pass callback function, which is run on every key in datastore.
>         Function have to accept key parameter.
> ```

"...parameter .\nKey is..." -> "...parameter, which is [a|of type] 'Buffer Object'."
___
*[examples/restAPI/pmemkvREST.py, line 79 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ohXb0Cn535pSgAIIJ:-M-ohXb1927JO2ULnfeG:b-nxn7pf) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L79)):*
> ```Python
>         Pass callback function, which is run on every key in datastore.
>         Function have to accept key parameter.
>         Key is Buffer Object. It's possible to directly access it's memory
> ```

it's -> its
___
*[examples/restAPI/pmemkvREST.py, line 82 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ohfHp8uL8zvh3V-63:-M-ohfHp8uL8zvh3V-64:bg2cc1) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L82)):*
> ```Python
>         through read-only memoryview() interface, or copy to volatile memory through
>         bytes().
>         To provide data to higher layer of framework, it have to be copied to
> ```

it has to
___
*[examples/restAPI/pmemkvREST.py, line 83 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ohne7-BdGg-24VxNe:-M-ohne81gDDBY05mFDU:b-oql7m5) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L83)):*
> ```Python
>         bytes().
>         To provide data to higher layer of framework, it have to be copied to
>         object in volatile memory. It's needed as access to key object outside
> ```

1. as an access
2. to the key object
___
*[examples/restAPI/pmemkvREST.py, line 84 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oi4L15LCHJbASZ77R:-M-oi4L15LCHJbASZ77S:b-hfm5so) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L84)):*
> ```Python
>         To provide data to higher layer of framework, it have to be copied to
>         object in volatile memory. It's needed as access to key object outside
>         of callback function may cause application crashes
> ```

of a callback
___
*[examples/restAPI/pmemkvREST.py, line 92 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ojpQm7aaJM5mhT1q1:-M-ojpQm7aaJM5mhT1q2:bmfuk6g) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L92)):*
> ```Python
>         print(req)
>         doc = json.load(req.bounded_stream)
>         """ Save data to datastore using dictionary interface """
> ```

to the datastore
___
*[examples/restAPI/run_example.py, line 58 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-omABa9pC_dNFXp_Q3:-M-omABa9pC_dNFXp_Q4:btsa7x3) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/run_example.py#L58)):*
> ```Python
>     if not os.path.exists(pool_path):
>         out, exit_status = pexpect.run(cmd, withexitstatus=True)
>         if exit_status !=  0:
> ```

double space before "0"
___
*[examples/restAPI/run_example.py, line 70 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-omQnb-GtaCqroO2B5:-M-omQnb-GtaCqroO2B6:b-guum4) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/run_example.py#L70)):*
> ```Python
>     create_pool(pool_path, pool_size)
>     server = RestApiRunner(pool_path)
>     print("Run server with pmemkv concurrent hash map as storage")
> ```

"pmemkv concurrent hash map" may not be perfectly understandable for people who are not aware of obj-cpp's container ;) I'd just simply say "cmap engine for storage" or something ;)
___
*[examples/restAPI/run_example.py, line 77 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-omnRj6EFVMfR7QdHb:-M-omnRj6EFVMfR7QdHc:b-k552q0) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/run_example.py#L77)):*
> ```Python
>     all_keys = requests.get("http://localhost:8000/db")
>     print(f"{'': <8}{all_keys}, {all_keys.content}")
>     print("Read back data:")
> ```

Read data back

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 4 of 8 files reviewed, 12 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ol6TN5pGpriJ-fCLW:-M-p0NBl2shhBoB0DDoU:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please update the "Examples" section in top-level README.md
</blockquote></details>

Done.

---
___
*[examples/restAPI/pmemkvREST.py, line 34 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oi_6UD9G5wNwwNe-G:-M-ox-Pc4bRz6PYqR6qn:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

double space at the end of the sentence -> replace this with '. '
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 77 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oh_LH-8uNQ3sqBpbK:-M-oxm9b7Z3rpCHy0U7M:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in the datastore
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 78 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oiGUP9fhj6YTCEEvJ:-M-p0JroEcZ2Mvpxkjx0:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"...parameter .\nKey is..." -> "...parameter, which is [a|of type] 'Buffer Object'."
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 79 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ohXb0Cn535pSgAIIJ:-M-oxR8n25g_8tY0E6cz:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's -> its
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 82 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ohfHp8uL8zvh3V-63:-M-oxuBf3GpfIuzgSC8t:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it has to
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 83 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ohne7-BdGg-24VxNe:-M-oy4CR1rBpxZCL3VPx:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L83)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. as an access
2. to the key object
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 84 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-oi4L15LCHJbASZ77R:-M-oy82dCHsD0NQa9n9y:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of a callback
</blockquote></details>

Done.
___
*[examples/restAPI/pmemkvREST.py, line 92 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-ojpQm7aaJM5mhT1q1:-M-oyBoD0UAjpor4Uia5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/pmemkvREST.py#L92)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to the datastore
</blockquote></details>

Done.
___
*[examples/restAPI/run_example.py, line 58 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-omABa9pC_dNFXp_Q3:-M-oyJ9qBSdQgV17PEnf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/run_example.py#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

double space before "0"
</blockquote></details>

Done.
___
*[examples/restAPI/run_example.py, line 70 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-omQnb-GtaCqroO2B5:-M-oyTBZ0OikEMaIrwYo:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/run_example.py#L70)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"pmemkv concurrent hash map" may not be perfectly understandable for people who are not aware of obj-cpp's container ;) I'd just simply say "cmap engine for storage" or something ;)
</blockquote></details>

Done.
___
*[examples/restAPI/run_example.py, line 77 at r4](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-omnRj6EFVMfR7QdHb:-M-oyWds5yoCjO105Hwe:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/c8a8fba159146effba75c93484f6feed79c3dd85/examples/restAPI/run_example.py#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Read data back
</blockquote></details>

Done.

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-trE319aeUfKizHusE:-M-trE327fzZxSMZTzjE:b-ttflas) (no related file):*
I believe you should drop the commit "Stop relying on undefined behaviour in tests" -it's not part of this PR and it's already merged ;)

---
___
*[README.md, line 52 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-tqMFA5a2OvKSZpKC6:-M-tqMFB9GadI9Z8dkKJ:bqk8yry) ([raw file](https://github.com/pmem/pmemkv-python/blob/ab38bf960f881ec6e7a4a3c1504b51dd4f917c8d/README.md#L52)):*
> ```Markdown
> We are using `/dev/shm` to
> [emulate persistent memory](http://pmem.io/2016/02/22/pm-emulation.html)
> in example.
> ```

example**s**
___
*[README.md, line 54 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-tqTbRCPX3QI99Txxs:-M-tqTbRCPX3QI99Txxt:bwsj2o1) ([raw file](https://github.com/pmem/pmemkv-python/blob/ab38bf960f881ec6e7a4a3c1504b51dd4f917c8d/README.md#L54)):*
> ```Markdown
> in example.
> 
> It can be found within this repository in [examples directory](https://github.com/pmem/pmemkv-python/tree/master/examples).
> ```

"it" -> "they"
___
*[README.md, line 55 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-tqYIKDv8PBTgnDYGk:-M-tqYIL8BWf5smC1Guu:b-xr73jt) ([raw file](https://github.com/pmem/pmemkv-python/blob/ab38bf960f881ec6e7a4a3c1504b51dd4f917c8d/README.md#L55)):*
> ```Markdown
> 
> It can be found within this repository in [examples directory](https://github.com/pmem/pmemkv-python/tree/master/examples).
> To execute the examples:
> ```

drop "the"

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-trE319aeUfKizHusE:-M-tsX7u5gX4l0iKEsvj:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you should drop the commit "Stop relying on undefined behaviour in tests" -it's not part of this PR and it's already merged ;)
</blockquote></details>

Done.

---
___
*[README.md, line 52 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-tqMFA5a2OvKSZpKC6:-M-tt7kg8dhvcm5Nskwa:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/ab38bf960f881ec6e7a4a3c1504b51dd4f917c8d/README.md#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

example**s**
</blockquote></details>

Done.
___
*[README.md, line 54 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-tqTbRCPX3QI99Txxs:-M-tt7HnCC78solVkIDt:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/ab38bf960f881ec6e7a4a3c1504b51dd4f917c8d/README.md#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"it" -> "they"
</blockquote></details>

Done.
___
*[README.md, line 55 at r5](https://reviewable.io/reviews/pmem/pmemkv-python/26#-M-tqYIKDv8PBTgnDYGk:-M-tt7Vy7rtmhqXWg-38:b-896fix) ([raw file](https://github.com/pmem/pmemkv-python/blob/ab38bf960f881ec6e7a4a3c1504b51dd4f917c8d/README.md#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

drop "the"
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-python/26#-:-M-txpaCEF92WY5t9ZZH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
